"""
test_ai_catalog.py
==================
Validates the generated ARD capability manifest (ai-catalog.json) against the
structural rules of the ai-catalog / ARD v0.9 specification, and checks that
index.html advertises it via the <link rel="ai-catalog"> discovery mechanism
(ARD spec §6.1).

The manifest is generated by scripts/build_docs.py from skills.json — these
tests guard the generated artifact, and the CI drift gate guards staleness.
"""

import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).parent.parent
CATALOG = REPO_ROOT / "ai-catalog.json"
MANIFEST = REPO_ROOT / "skills.json"

URN_RE = re.compile(r"^urn:ai:sushegaad\.github\.io:grc:[a-z0-9]+(-[a-z0-9]+)*$")
CATALOG_URL = ("https://sushegaad.github.io/"
               "Claude-Skills-Governance-Risk-and-Compliance/ai-catalog.json")


def _catalog():
    return json.loads(CATALOG.read_text(encoding="utf-8"))


class TestCatalogStructure:
    def test_catalog_exists_and_parses(self):
        assert CATALOG.exists(), "ai-catalog.json missing — run scripts/build_docs.py"
        data = _catalog()
        assert data["specVersion"] == "1.0"
        assert data["host"]["displayName"]

    def test_entry_count_matches_manifest(self):
        skills = json.loads(MANIFEST.read_text(encoding="utf-8"))["skills"]
        assert len(_catalog()["entries"]) == len(skills)

    def test_entries_cover_all_plugins(self):
        skills = json.loads(MANIFEST.read_text(encoding="utf-8"))["skills"]
        expected = {f'urn:ai:sushegaad.github.io:grc:{s["plugin"]}' for s in skills}
        actual = {e["identifier"] for e in _catalog()["entries"]}
        assert actual == expected

    def test_entry_required_fields_and_urn_format(self):
        for e in _catalog()["entries"]:
            assert URN_RE.match(e["identifier"]), e["identifier"]
            assert e["displayName"].strip()
            assert e["type"] == "application/ai-skill+md"

    def test_value_or_reference_exclusive(self):
        """Spec §3.4: exactly one of url / data per entry."""
        for e in _catalog()["entries"]:
            assert ("url" in e) != ("data" in e), e["identifier"]

    def test_representative_queries_sizing(self):
        """Spec §4.2: SHOULD contain 2–5 natural-language examples."""
        for e in _catalog()["entries"]:
            q = e.get("representativeQueries", [])
            assert 2 <= len(q) <= 5, f'{e["identifier"]}: {len(q)} queries'
            assert all(isinstance(x, str) and len(x) > 10 for x in q)

    def test_urls_resolve_to_source_skill_md(self):
        """Each entry's url must map to a real SKILL.md in this repo."""
        prefix = ("https://github.com/Sushegaad/"
                  "Claude-Skills-Governance-Risk-and-Compliance/raw/main/")
        for e in _catalog()["entries"]:
            assert e["url"].startswith(prefix), e["identifier"]
            local = REPO_ROOT / e["url"][len(prefix):]
            assert local.exists(), f'{e["identifier"]}: {local} not found'

    def test_updated_at_iso8601(self):
        for e in _catalog()["entries"]:
            assert re.match(r"^\d{4}-\d{2}-\d{2}T00:00:00Z$", e["updatedAt"])


class TestDiscoveryLinkTag:
    def test_index_head_advertises_catalog(self):
        """ARD spec §6.1: <link rel="ai-catalog" href="..."> in the head."""
        html = (REPO_ROOT / "index.html").read_text(encoding="utf-8")
        head = html.split("</head>", 1)[0]
        m = re.search(r'<link[^>]*rel="ai-catalog"[^>]*>', head)
        assert m, 'no <link rel="ai-catalog"> in index.html <head>'
        assert CATALOG_URL in m.group(0)
